version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-commerce-store-api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    image: postgres:latest
    container_name: e-commerce-store-api-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
    driver: local
