services:
  app:
    build:
      context: .
      dockerfile: dockerfile.prod
    container_name: e-commerce-store-api-prod
    env_file:
      - .env.prod
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
      - /app/node_modules
