services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: e-commerce-store-api-dev
    env_file:
      - .env.dev
    environment:
      HOST: postgres
      # DO NOT CHANGE
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    image: postgres:latest
    container_name: e-commerce-store-api-db-dev
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  postgres-data-dev:
    driver: local
