import {describe, expect} from "@jest/globals";
import processSQLProductBasicData from "../src/routes/routerUtilities/processSQLProductBasicData";
import Decimal from "decimal.js";

import {
  ProductBasicDataDatabase,
  ProductBasicDataResponse,
} from "./types/tests";

//SECTION - test no. 1
describe("processSQLProductBasicData: ", () => {
  it("Should process SQL rows and return the expected response: GET http://localhost:4000/category/sneakers", () => {
    const inputRows: ProductBasicDataDatabase[] = [
      {
        id: "a1524b05-64a6-4d2d-9d6b-6ab57b804923",
        brand: "Zalton",
        model: "AirFlex 5000",
        gender: "men",
        category: "sneakers",
        material: "mesh",
        season: "all_season",
        short_description: "Versatile Running Shoes",
        description:
          "The Zalton AirFlex 5000 delivers the same responsive cushioning that runners love.",
        features: ["Responsive cushioning", "Breathable mesh upper"],
        price: new Decimal("129.99"),
        initial_price: new Decimal("149.99"),
        rating_reviews: 120,
        rating_value: new Decimal("4.5"),
        thumbnail:
          "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/buty-meskie-dunk-low-retro-wwlDHh.png",
        color: "white",
        size: "40",
        count: 20,
      },
      {
        id: "a1524b05-64a6-4d2d-9d6b-6ab57b804923",
        brand: "Zalton",
        model: "AirFlex 5000",
        gender: "men",
        category: "sneakers",
        material: "mesh",
        season: "all_season",
        short_description: "Versatile Running Shoes",
        description:
          "The Zalton AirFlex 5000 delivers the same responsive cushioning that runners love.",
        features: ["Responsive cushioning", "Breathable mesh upper"],
        price: new Decimal("129.99"),
        initial_price: new Decimal("149.99"),
        rating_reviews: 120,
        rating_value: new Decimal("4.5"),
        thumbnail:
          "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/buty-meskie-dunk-low-retro-wwlDHh.png",
        color: "white",
        size: "41",
        count: 15,
      },
      {
        id: "a1524b05-64a6-4d2d-9d6b-6ab57b804923",
        brand: "Zalton",
        model: "AirFlex 5000",
        gender: "men",
        category: "sneakers",
        material: "mesh",
        season: "all_season",
        short_description: "Versatile Running Shoes",
        description:
          "The Zalton AirFlex 5000 delivers the same responsive cushioning that runners love.",
        features: ["Responsive cushioning", "Breathable mesh upper"],
        price: new Decimal("129.99"),
        initial_price: new Decimal("149.99"),
        rating_reviews: 120,
        rating_value: new Decimal("4.5"),
        thumbnail:
          "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/buty-meskie-dunk-low-retro-wwlDHh.png",
        color: "white",
        size: "42",
        count: 10,
      },
      {
        id: "a1524b05-64a6-4d2d-9d6b-6ab57b804923",
        brand: "Zalton",
        model: "AirFlex 5000",
        gender: "men",
        category: "sneakers",
        material: "mesh",
        season: "all_season",
        short_description: "Versatile Running Shoes",
        description:
          "The Zalton AirFlex 5000 delivers the same responsive cushioning that runners love.",
        features: ["Responsive cushioning", "Breathable mesh upper"],
        price: new Decimal("129.99"),
        initial_price: new Decimal("149.99"),
        rating_reviews: 120,
        rating_value: new Decimal("4.5"),
        thumbnail:
          "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/buty-meskie-dunk-low-retro-wwlDHh.png",
        color: "white",
        size: "43",
        count: 12,
      },
      {
        id: "a1524b05-64a6-4d2d-9d6b-6ab57b804923",
        brand: "Zalton",
        model: "AirFlex 5000",
        gender: "men",
        category: "sneakers",
        material: "mesh",
        season: "all_season",
        short_description: "Versatile Running Shoes",
        description:
          "The Zalton AirFlex 5000 delivers the same responsive cushioning that runners love.",
        features: ["Responsive cushioning", "Breathable mesh upper"],
        price: new Decimal("129.99"),
        initial_price: new Decimal("149.99"),
        rating_reviews: 120,
        rating_value: new Decimal("4.5"),
        thumbnail:
          "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/buty-meskie-dunk-low-retro-wwlDHh.png",
        color: "white",
        size: "44",
        count: 8,
      },
      {
        id: "c8837c8e-3aeb-4483-81c4-233127a2b58d",
        brand: "UrbanStep",
        model: "AirStride 3000",
        gender: "men",
        category: "sneakers",
        material: "mesh",
        season: "winter",
        short_description: "Versatile Running Shoes",
        description:
          "The UrbanStep AirStride 3000 offers a balanced mix of cushioning and flexibility for runners.",
        features: ["Lightweight mesh upper", "EVA sockliner"],
        price: new Decimal("70.00"),
        initial_price: new Decimal("79.99"),
        rating_reviews: 55,
        rating_value: new Decimal("4.4"),
        thumbnail:
          "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f228c7a1-177d-483b-ba52-a5e41f43fbd2/buty-meskie-air-max-plus-utility-HkwSWp.png",
        color: "black",
        size: "39",
        count: 14,
      },
      {
        id: "c8837c8e-3aeb-4483-81c4-233127a2b58d",
        brand: "UrbanStep",
        model: "AirStride 3000",
        gender: "men",
        category: "sneakers",
        material: "mesh",
        season: "winter",
        short_description: "Versatile Running Shoes",
        description:
          "The UrbanStep AirStride 3000 offers a balanced mix of cushioning and flexibility for runners.",
        features: ["Lightweight mesh upper", "EVA sockliner"],
        price: new Decimal("70.00"),
        initial_price: new Decimal("79.99"),
        rating_reviews: 55,
        rating_value: new Decimal("4.4"),
        thumbnail:
          "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f228c7a1-177d-483b-ba52-a5e41f43fbd2/buty-meskie-air-max-plus-utility-HkwSWp.png",
        color: "black",
        size: "40",
        count: 20,
      },
      {
        id: "c8837c8e-3aeb-4483-81c4-233127a2b58d",
        brand: "UrbanStep",
        model: "AirStride 3000",
        gender: "men",
        category: "sneakers",
        material: "mesh",
        season: "winter",
        short_description: "Versatile Running Shoes",
        description:
          "The UrbanStep AirStride 3000 offers a balanced mix of cushioning and flexibility for runners.",
        features: ["Lightweight mesh upper", "EVA sockliner"],
        price: new Decimal("70.00"),
        initial_price: new Decimal("79.99"),
        rating_reviews: 55,
        rating_value: new Decimal("4.4"),
        thumbnail:
          "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f228c7a1-177d-483b-ba52-a5e41f43fbd2/buty-meskie-air-max-plus-utility-HkwSWp.png",
        color: "black",
        size: "41",
        count: 15,
      },
      {
        id: "c8837c8e-3aeb-4483-81c4-233127a2b58d",
        brand: "UrbanStep",
        model: "AirStride 3000",
        gender: "men",
        category: "sneakers",
        material: "mesh",
        season: "winter",
        short_description: "Versatile Running Shoes",
        description:
          "The UrbanStep AirStride 3000 offers a balanced mix of cushioning and flexibility for runners.",
        features: ["Lightweight mesh upper", "EVA sockliner"],
        price: new Decimal("70.00"),
        initial_price: new Decimal("79.99"),
        rating_reviews: 55,
        rating_value: new Decimal("4.4"),
        thumbnail:
          "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f228c7a1-177d-483b-ba52-a5e41f43fbd2/buty-meskie-air-max-plus-utility-HkwSWp.png",
        color: "black",
        size: "42",
        count: 10,
      },
      {
        id: "c8837c8e-3aeb-4483-81c4-233127a2b58d",
        brand: "UrbanStep",
        model: "AirStride 3000",
        gender: "men",
        category: "sneakers",
        material: "mesh",
        season: "winter",
        short_description: "Versatile Running Shoes",
        description:
          "The UrbanStep AirStride 3000 offers a balanced mix of cushioning and flexibility for runners.",
        features: ["Lightweight mesh upper", "EVA sockliner"],
        price: new Decimal("70.00"),
        initial_price: new Decimal("79.99"),
        rating_reviews: 55,
        rating_value: new Decimal("4.4"),
        thumbnail:
          "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f228c7a1-177d-483b-ba52-a5e41f43fbd2/buty-meskie-air-max-plus-utility-HkwSWp.png",
        color: "black",
        size: "43",
        count: 12,
      },
    ];

    const expectedOutput: ProductBasicDataResponse[] = [
      {
        id: "a1524b05-64a6-4d2d-9d6b-6ab57b804923",
        brand: "Zalton",
        model: "AirFlex 5000",
        gender: "men",
        category: "sneakers",
        material: "mesh",
        season: "all_season",
        short_description: "Versatile Running Shoes",
        description:
          "The Zalton AirFlex 5000 delivers the same responsive cushioning that runners love.",
        features: ["Responsive cushioning", "Breathable mesh upper"],
        price: new Decimal("129.99"),
        initial_price: new Decimal("149.99"),
        rating_reviews: 120,
        rating_value: new Decimal("4.5"),
        thumbnail:
          "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/buty-meskie-dunk-low-retro-wwlDHh.png",
        color: "white",
        stock_array: [
          {size: "40", count: 20},
          {size: "41", count: 15},
          {size: "42", count: 10},
          {size: "43", count: 12},
          {size: "44", count: 8},
        ],
      },
      {
        id: "c8837c8e-3aeb-4483-81c4-233127a2b58d",
        brand: "UrbanStep",
        model: "AirStride 3000",
        gender: "men",
        category: "sneakers",
        material: "mesh",
        season: "winter",
        short_description: "Versatile Running Shoes",
        description:
          "The UrbanStep AirStride 3000 offers a balanced mix of cushioning and flexibility for runners.",
        features: ["Lightweight mesh upper", "EVA sockliner"],
        price: new Decimal("70.00"),
        initial_price: new Decimal("79.99"),
        rating_reviews: 55,
        rating_value: new Decimal("4.4"),
        thumbnail:
          "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f228c7a1-177d-483b-ba52-a5e41f43fbd2/buty-meskie-air-max-plus-utility-HkwSWp.png",
        color: "black",
        stock_array: [
          {size: "39", count: 14},
          {size: "40", count: 20},
          {size: "41", count: 15},
          {size: "42", count: 10},
          {size: "43", count: 12},
        ],
      },
    ];

    const result = processSQLProductBasicData(inputRows);

    expect(result).toEqual(expectedOutput);
  });

  //SECTION - test no. 2
  it("should handle empty input rows", () => {
    const inputRows: ProductBasicDataDatabase[] = [];
    const expectedOutput: ProductBasicDataResponse[] = [];

    const result = processSQLProductBasicData(inputRows);

    expect(result).toEqual(expectedOutput);
  });
});

//SECTION - test no. 3
it("Should process SQL rows and return the expected response: GET http://localhost:4000/gender/men/", () => {
  const inputRows: ProductBasicDataDatabase[] = [
    {
      id: "a1524b05-64a6-4d2d-9d6b-6ab57b804923",
      brand: "Zalton",
      model: "AirFlex 5000",
      gender: "men",
      category: "sneakers",
      material: "mesh",
      season: "all_season",
      short_description: "Versatile Running Shoes",
      description:
        "The Zalton AirFlex 5000 delivers the same responsive cushioning that runners love.",
      features: ["Responsive cushioning", "Breathable mesh upper"],
      price: new Decimal("129.99"),
      initial_price: new Decimal("149.99"),
      rating_reviews: 120,
      rating_value: new Decimal("4.5"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/buty-meskie-dunk-low-retro-wwlDHh.png",
      color: "white",
      size: "40",
      count: 20,
    },
    {
      id: "a1524b05-64a6-4d2d-9d6b-6ab57b804923",
      brand: "Zalton",
      model: "AirFlex 5000",
      gender: "men",
      category: "sneakers",
      material: "mesh",
      season: "all_season",
      short_description: "Versatile Running Shoes",
      description:
        "The Zalton AirFlex 5000 delivers the same responsive cushioning that runners love.",
      features: ["Responsive cushioning", "Breathable mesh upper"],
      price: new Decimal("129.99"),
      initial_price: new Decimal("149.99"),
      rating_reviews: 120,
      rating_value: new Decimal("4.5"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/buty-meskie-dunk-low-retro-wwlDHh.png",
      color: "white",
      size: "41",
      count: 15,
    },
    {
      id: "a1524b05-64a6-4d2d-9d6b-6ab57b804923",
      brand: "Zalton",
      model: "AirFlex 5000",
      gender: "men",
      category: "sneakers",
      material: "mesh",
      season: "all_season",
      short_description: "Versatile Running Shoes",
      description:
        "The Zalton AirFlex 5000 delivers the same responsive cushioning that runners love.",
      features: ["Responsive cushioning", "Breathable mesh upper"],
      price: new Decimal("129.99"),
      initial_price: new Decimal("149.99"),
      rating_reviews: 120,
      rating_value: new Decimal("4.5"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/buty-meskie-dunk-low-retro-wwlDHh.png",
      color: "white",
      size: "42",
      count: 10,
    },
    {
      id: "a1524b05-64a6-4d2d-9d6b-6ab57b804923",
      brand: "Zalton",
      model: "AirFlex 5000",
      gender: "men",
      category: "sneakers",
      material: "mesh",
      season: "all_season",
      short_description: "Versatile Running Shoes",
      description:
        "The Zalton AirFlex 5000 delivers the same responsive cushioning that runners love.",
      features: ["Responsive cushioning", "Breathable mesh upper"],
      price: new Decimal("129.99"),
      initial_price: new Decimal("149.99"),
      rating_reviews: 120,
      rating_value: new Decimal("4.5"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/buty-meskie-dunk-low-retro-wwlDHh.png",
      color: "white",
      size: "43",
      count: 12,
    },
    {
      id: "a1524b05-64a6-4d2d-9d6b-6ab57b804923",
      brand: "Zalton",
      model: "AirFlex 5000",
      gender: "men",
      category: "sneakers",
      material: "mesh",
      season: "all_season",
      short_description: "Versatile Running Shoes",
      description:
        "The Zalton AirFlex 5000 delivers the same responsive cushioning that runners love.",
      features: ["Responsive cushioning", "Breathable mesh upper"],
      price: new Decimal("129.99"),
      initial_price: new Decimal("149.99"),
      rating_reviews: 120,
      rating_value: new Decimal("4.5"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/buty-meskie-dunk-low-retro-wwlDHh.png",
      color: "white",
      size: "44",
      count: 8,
    },
    {
      id: "30984c42-37de-4377-8de3-2d16f4897a18",
      brand: "Trekster",
      model: "Future Rider X1",
      gender: "men",
      category: "casual",
      material: "suede",
      season: "all_season",
      short_description: "Retro-Inspired Casual Sneakers",
      description:
        "The Trekster Future Rider X1 combines retro style with modern comfort.",
      features: ["Rider Foam midsole", "Suede and mesh upper"],
      price: new Decimal("79.99"),
      initial_price: new Decimal("89.99"),
      rating_reviews: 60,
      rating_value: new Decimal("4.3"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a8254cc4-b776-47b2-898f-7e6e1f564c94/buty-meskie-air-force-1-07-QMx6sn.png",
      color: "black",
      size: "41",
      count: 20,
    },
    {
      id: "30984c42-37de-4377-8de3-2d16f4897a18",
      brand: "Trekster",
      model: "Future Rider X1",
      gender: "men",
      category: "casual",
      material: "suede",
      season: "all_season",
      short_description: "Retro-Inspired Casual Sneakers",
      description:
        "The Trekster Future Rider X1 combines retro style with modern comfort.",
      features: ["Rider Foam midsole", "Suede and mesh upper"],
      price: new Decimal("79.99"),
      initial_price: new Decimal("89.99"),
      rating_reviews: 60,
      rating_value: new Decimal("4.3"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a8254cc4-b776-47b2-898f-7e6e1f564c94/buty-meskie-air-force-1-07-QMx6sn.png",
      color: "black",
      size: "42",
      count: 15,
    },
    {
      id: "30984c42-37de-4377-8de3-2d16f4897a18",
      brand: "Trekster",
      model: "Future Rider X1",
      gender: "men",
      category: "casual",
      material: "suede",
      season: "all_season",
      short_description: "Retro-Inspired Casual Sneakers",
      description:
        "The Trekster Future Rider X1 combines retro style with modern comfort.",
      features: ["Rider Foam midsole", "Suede and mesh upper"],
      price: new Decimal("79.99"),
      initial_price: new Decimal("89.99"),
      rating_reviews: 60,
      rating_value: new Decimal("4.3"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a8254cc4-b776-47b2-898f-7e6e1f564c94/buty-meskie-air-force-1-07-QMx6sn.png",
      color: "black",
      size: "43",
      count: 12,
    },
    {
      id: "30984c42-37de-4377-8de3-2d16f4897a18",
      brand: "Trekster",
      model: "Future Rider X1",
      gender: "men",
      category: "casual",
      material: "suede",
      season: "all_season",
      short_description: "Retro-Inspired Casual Sneakers",
      description:
        "The Trekster Future Rider X1 combines retro style with modern comfort.",
      features: ["Rider Foam midsole", "Suede and mesh upper"],
      price: new Decimal("79.99"),
      initial_price: new Decimal("89.99"),
      rating_reviews: 60,
      rating_value: new Decimal("4.3"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a8254cc4-b776-47b2-898f-7e6e1f564c94/buty-meskie-air-force-1-07-QMx6sn.png",
      color: "black",
      size: "44",
      count: 8,
    },
    {
      id: "30984c42-37de-4377-8de3-2d16f4897a18",
      brand: "Trekster",
      model: "Future Rider X1",
      gender: "men",
      category: "casual",
      material: "suede",
      season: "all_season",
      short_description: "Retro-Inspired Casual Sneakers",
      description:
        "The Trekster Future Rider X1 combines retro style with modern comfort.",
      features: ["Rider Foam midsole", "Suede and mesh upper"],
      price: new Decimal("79.99"),
      initial_price: new Decimal("89.99"),
      rating_reviews: 60,
      rating_value: new Decimal("4.3"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a8254cc4-b776-47b2-898f-7e6e1f564c94/buty-meskie-air-force-1-07-QMx6sn.png",
      color: "black",
      size: "45",
      count: 10,
    },
    {
      id: "c8837c8e-3aeb-4483-81c4-233127a2b58d",
      brand: "UrbanStep",
      model: "AirStride 3000",
      gender: "men",
      category: "sneakers",
      material: "mesh",
      season: "winter",
      short_description: "Versatile Running Shoes",
      description:
        "The UrbanStep AirStride 3000 offers a balanced mix of cushioning and flexibility for runners.",
      features: ["Lightweight mesh upper", "EVA sockliner"],
      price: new Decimal("70.00"),
      initial_price: new Decimal("79.99"),
      rating_reviews: 55,
      rating_value: new Decimal("4.4"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f228c7a1-177d-483b-ba52-a5e41f43fbd2/buty-meskie-air-max-plus-utility-HkwSWp.png",
      color: "black",
      size: "39",
      count: 14,
    },
    {
      id: "c8837c8e-3aeb-4483-81c4-233127a2b58d",
      brand: "UrbanStep",
      model: "AirStride 3000",
      gender: "men",
      category: "sneakers",
      material: "mesh",
      season: "winter",
      short_description: "Versatile Running Shoes",
      description:
        "The UrbanStep AirStride 3000 offers a balanced mix of cushioning and flexibility for runners.",
      features: ["Lightweight mesh upper", "EVA sockliner"],
      price: new Decimal("70.00"),
      initial_price: new Decimal("79.99"),
      rating_reviews: 55,
      rating_value: new Decimal("4.4"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f228c7a1-177d-483b-ba52-a5e41f43fbd2/buty-meskie-air-max-plus-utility-HkwSWp.png",
      color: "black",
      size: "40",
      count: 20,
    },
    {
      id: "c8837c8e-3aeb-4483-81c4-233127a2b58d",
      brand: "UrbanStep",
      model: "AirStride 3000",
      gender: "men",
      category: "sneakers",
      material: "mesh",
      season: "winter",
      short_description: "Versatile Running Shoes",
      description:
        "The UrbanStep AirStride 3000 offers a balanced mix of cushioning and flexibility for runners.",
      features: ["Lightweight mesh upper", "EVA sockliner"],
      price: new Decimal("70.00"),
      initial_price: new Decimal("79.99"),
      rating_reviews: 55,
      rating_value: new Decimal("4.4"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f228c7a1-177d-483b-ba52-a5e41f43fbd2/buty-meskie-air-max-plus-utility-HkwSWp.png",
      color: "black",
      size: "41",
      count: 15,
    },
    {
      id: "c8837c8e-3aeb-4483-81c4-233127a2b58d",
      brand: "UrbanStep",
      model: "AirStride 3000",
      gender: "men",
      category: "sneakers",
      material: "mesh",
      season: "winter",
      short_description: "Versatile Running Shoes",
      description:
        "The UrbanStep AirStride 3000 offers a balanced mix of cushioning and flexibility for runners.",
      features: ["Lightweight mesh upper", "EVA sockliner"],
      price: new Decimal("70.00"),
      initial_price: new Decimal("79.99"),
      rating_reviews: 55,
      rating_value: new Decimal("4.4"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f228c7a1-177d-483b-ba52-a5e41f43fbd2/buty-meskie-air-max-plus-utility-HkwSWp.png",
      color: "black",
      size: "42",
      count: 10,
    },
    {
      id: "c8837c8e-3aeb-4483-81c4-233127a2b58d",
      brand: "UrbanStep",
      model: "AirStride 3000",
      gender: "men",
      category: "sneakers",
      material: "mesh",
      season: "winter",
      short_description: "Versatile Running Shoes",
      description:
        "The UrbanStep AirStride 3000 offers a balanced mix of cushioning and flexibility for runners.",
      features: ["Lightweight mesh upper", "EVA sockliner"],
      price: new Decimal("70.00"),
      initial_price: new Decimal("79.99"),
      rating_reviews: 55,
      rating_value: new Decimal("4.4"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f228c7a1-177d-483b-ba52-a5e41f43fbd2/buty-meskie-air-max-plus-utility-HkwSWp.png",
      color: "black",
      size: "43",
      count: 12,
    },
    {
      id: "25d3eef0-d854-4d1e-b11b-bec75d5da9c5",
      brand: "UrbanRun",
      model: "AirFlow 14",
      gender: "men",
      category: "running",
      material: "mesh",
      season: "all_season",
      short_description: "Plush Running Shoes",
      description:
        "The UrbanRun AirFlow 14 offers plush cushioning and smooth transitions for neutral runners.",
      features: ["DNA Loft cushioning", "Segmented Crash Pad"],
      price: new Decimal("129.95"),
      initial_price: new Decimal("149.99"),
      rating_reviews: 80,
      rating_value: new Decimal("4.8"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd8662cc-1947-4ead-b02f-a474142e7430/buty-air-max-dn-se-4PdLm8.png",
      color: "black",
      size: "40",
      count: 14,
    },
    {
      id: "25d3eef0-d854-4d1e-b11b-bec75d5da9c5",
      brand: "UrbanRun",
      model: "AirFlow 14",
      gender: "men",
      category: "running",
      material: "mesh",
      season: "all_season",
      short_description: "Plush Running Shoes",
      description:
        "The UrbanRun AirFlow 14 offers plush cushioning and smooth transitions for neutral runners.",
      features: ["DNA Loft cushioning", "Segmented Crash Pad"],
      price: new Decimal("129.95"),
      initial_price: new Decimal("149.99"),
      rating_reviews: 80,
      rating_value: new Decimal("4.8"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd8662cc-1947-4ead-b02f-a474142e7430/buty-air-max-dn-se-4PdLm8.png",
      color: "black",
      size: "41",
      count: 20,
    },
    {
      id: "25d3eef0-d854-4d1e-b11b-bec75d5da9c5",
      brand: "UrbanRun",
      model: "AirFlow 14",
      gender: "men",
      category: "running",
      material: "mesh",
      season: "all_season",
      short_description: "Plush Running Shoes",
      description:
        "The UrbanRun AirFlow 14 offers plush cushioning and smooth transitions for neutral runners.",
      features: ["DNA Loft cushioning", "Segmented Crash Pad"],
      price: new Decimal("129.95"),
      initial_price: new Decimal("149.99"),
      rating_reviews: 80,
      rating_value: new Decimal("4.8"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd8662cc-1947-4ead-b02f-a474142e7430/buty-air-max-dn-se-4PdLm8.png",
      color: "black",
      size: "42",
      count: 15,
    },
    {
      id: "25d3eef0-d854-4d1e-b11b-bec75d5da9c5",
      brand: "UrbanRun",
      model: "AirFlow 14",
      gender: "men",
      category: "running",
      material: "mesh",
      season: "all_season",
      short_description: "Plush Running Shoes",
      description:
        "The UrbanRun AirFlow 14 offers plush cushioning and smooth transitions for neutral runners.",
      features: ["DNA Loft cushioning", "Segmented Crash Pad"],
      price: new Decimal("129.95"),
      initial_price: new Decimal("149.99"),
      rating_reviews: 80,
      rating_value: new Decimal("4.8"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd8662cc-1947-4ead-b02f-a474142e7430/buty-air-max-dn-se-4PdLm8.png",
      color: "black",
      size: "43",
      count: 10,
    },
    {
      id: "25d3eef0-d854-4d1e-b11b-bec75d5da9c5",
      brand: "UrbanRun",
      model: "AirFlow 14",
      gender: "men",
      category: "running",
      material: "mesh",
      season: "all_season",
      short_description: "Plush Running Shoes",
      description:
        "The UrbanRun AirFlow 14 offers plush cushioning and smooth transitions for neutral runners.",
      features: ["DNA Loft cushioning", "Segmented Crash Pad"],
      price: new Decimal("129.95"),
      initial_price: new Decimal("149.99"),
      rating_reviews: 80,
      rating_value: new Decimal("4.8"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd8662cc-1947-4ead-b02f-a474142e7430/buty-air-max-dn-se-4PdLm8.png",
      color: "black",
      size: "44",
      count: 12,
    },
    {
      id: "0d55026d-ff26-487f-9183-064e801a150e",
      brand: "StrideMax",
      model: "GelBliss 230",
      gender: "men",
      category: "running",
      material: "synthetic",
      season: "all_season",
      short_description: "Premium Cushioned Running Shoes",
      description:
        "The StrideMax GelBliss 230 offers premium cushioning and support for long-distance runners.",
      features: ["GEL cushioning technology", "Breathable mesh upper"],
      price: new Decimal("149.95"),
      initial_price: new Decimal("169.99"),
      rating_reviews: 90,
      rating_value: new Decimal("4.7"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/78913680-cf99-47a0-b03c-9484cc689f24/buty-p-6000-B011cg.png",
      color: "white",
      size: "40",
      count: 15,
    },
    {
      id: "0d55026d-ff26-487f-9183-064e801a150e",
      brand: "StrideMax",
      model: "GelBliss 230",
      gender: "men",
      category: "running",
      material: "synthetic",
      season: "all_season",
      short_description: "Premium Cushioned Running Shoes",
      description:
        "The StrideMax GelBliss 230 offers premium cushioning and support for long-distance runners.",
      features: ["GEL cushioning technology", "Breathable mesh upper"],
      price: new Decimal("149.95"),
      initial_price: new Decimal("169.99"),
      rating_reviews: 90,
      rating_value: new Decimal("4.7"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/78913680-cf99-47a0-b03c-9484cc689f24/buty-p-6000-B011cg.png",
      color: "white",
      size: "41",
      count: 18,
    },
    {
      id: "0d55026d-ff26-487f-9183-064e801a150e",
      brand: "StrideMax",
      model: "GelBliss 230",
      gender: "men",
      category: "running",
      material: "synthetic",
      season: "all_season",
      short_description: "Premium Cushioned Running Shoes",
      description:
        "The StrideMax GelBliss 230 offers premium cushioning and support for long-distance runners.",
      features: ["GEL cushioning technology", "Breathable mesh upper"],
      price: new Decimal("149.95"),
      initial_price: new Decimal("169.99"),
      rating_reviews: 90,
      rating_value: new Decimal("4.7"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/78913680-cf99-47a0-b03c-9484cc689f24/buty-p-6000-B011cg.png",
      color: "white",
      size: "42",
      count: 22,
    },
    {
      id: "0d55026d-ff26-487f-9183-064e801a150e",
      brand: "StrideMax",
      model: "GelBliss 230",
      gender: "men",
      category: "running",
      material: "synthetic",
      season: "all_season",
      short_description: "Premium Cushioned Running Shoes",
      description:
        "The StrideMax GelBliss 230 offers premium cushioning and support for long-distance runners.",
      features: ["GEL cushioning technology", "Breathable mesh upper"],
      price: new Decimal("149.95"),
      initial_price: new Decimal("169.99"),
      rating_reviews: 90,
      rating_value: new Decimal("4.7"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/78913680-cf99-47a0-b03c-9484cc689f24/buty-p-6000-B011cg.png",
      color: "white",
      size: "43",
      count: 15,
    },
    {
      id: "0d55026d-ff26-487f-9183-064e801a150e",
      brand: "StrideMax",
      model: "GelBliss 230",
      gender: "men",
      category: "running",
      material: "synthetic",
      season: "all_season",
      short_description: "Premium Cushioned Running Shoes",
      description:
        "The StrideMax GelBliss 230 offers premium cushioning and support for long-distance runners.",
      features: ["GEL cushioning technology", "Breathable mesh upper"],
      price: new Decimal("149.95"),
      initial_price: new Decimal("169.99"),
      rating_reviews: 90,
      rating_value: new Decimal("4.7"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/78913680-cf99-47a0-b03c-9484cc689f24/buty-p-6000-B011cg.png",
      color: "white",
      size: "44",
      count: 20,
    },
  ];

  const expectedOutput: ProductBasicDataResponse[] = [
    {
      id: "a1524b05-64a6-4d2d-9d6b-6ab57b804923",
      brand: "Zalton",
      model: "AirFlex 5000",
      gender: "men",
      category: "sneakers",
      material: "mesh",
      season: "all_season",
      short_description: "Versatile Running Shoes",
      description:
        "The Zalton AirFlex 5000 delivers the same responsive cushioning that runners love.",
      features: ["Responsive cushioning", "Breathable mesh upper"],
      price: new Decimal("129.99"),
      initial_price: new Decimal("149.99"),
      rating_reviews: 120,
      rating_value: new Decimal("4.5"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a3e7dead-1ad2-4c40-996d-93ebc9df0fca/buty-meskie-dunk-low-retro-wwlDHh.png",
      color: "white",
      stock_array: [
        {
          size: "40",
          count: 20,
        },
        {
          size: "41",
          count: 15,
        },
        {
          size: "42",
          count: 10,
        },
        {
          size: "43",
          count: 12,
        },
        {
          size: "44",
          count: 8,
        },
      ],
    },
    {
      id: "30984c42-37de-4377-8de3-2d16f4897a18",
      brand: "Trekster",
      model: "Future Rider X1",
      gender: "men",
      category: "casual",
      material: "suede",
      season: "all_season",
      short_description: "Retro-Inspired Casual Sneakers",
      description:
        "The Trekster Future Rider X1 combines retro style with modern comfort.",
      features: ["Rider Foam midsole", "Suede and mesh upper"],
      price: new Decimal("79.99"),
      initial_price: new Decimal("89.99"),
      rating_reviews: 60,
      rating_value: new Decimal("4.3"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a8254cc4-b776-47b2-898f-7e6e1f564c94/buty-meskie-air-force-1-07-QMx6sn.png",
      color: "black",
      stock_array: [
        {
          size: "41",
          count: 20,
        },
        {
          size: "42",
          count: 15,
        },
        {
          size: "43",
          count: 12,
        },
        {
          size: "44",
          count: 8,
        },
        {
          size: "45",
          count: 10,
        },
      ],
    },
    {
      id: "c8837c8e-3aeb-4483-81c4-233127a2b58d",
      brand: "UrbanStep",
      model: "AirStride 3000",
      gender: "men",
      category: "sneakers",
      material: "mesh",
      season: "winter",
      short_description: "Versatile Running Shoes",
      description:
        "The UrbanStep AirStride 3000 offers a balanced mix of cushioning and flexibility for runners.",
      features: ["Lightweight mesh upper", "EVA sockliner"],
      price: new Decimal("70.00"),
      initial_price: new Decimal("79.99"),
      rating_reviews: 55,
      rating_value: new Decimal("4.4"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f228c7a1-177d-483b-ba52-a5e41f43fbd2/buty-meskie-air-max-plus-utility-HkwSWp.png",
      color: "black",
      stock_array: [
        {
          size: "39",
          count: 14,
        },
        {
          size: "40",
          count: 20,
        },
        {
          size: "41",
          count: 15,
        },
        {
          size: "42",
          count: 10,
        },
        {
          size: "43",
          count: 12,
        },
      ],
    },
    {
      id: "25d3eef0-d854-4d1e-b11b-bec75d5da9c5",
      brand: "UrbanRun",
      model: "AirFlow 14",
      gender: "men",
      category: "running",
      material: "mesh",
      season: "all_season",
      short_description: "Plush Running Shoes",
      description:
        "The UrbanRun AirFlow 14 offers plush cushioning and smooth transitions for neutral runners.",
      features: ["DNA Loft cushioning", "Segmented Crash Pad"],
      price: new Decimal("129.95"),
      initial_price: new Decimal("149.99"),
      rating_reviews: 80,
      rating_value: new Decimal("4.8"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cd8662cc-1947-4ead-b02f-a474142e7430/buty-air-max-dn-se-4PdLm8.png",
      color: "black",
      stock_array: [
        {
          size: "40",
          count: 14,
        },
        {
          size: "41",
          count: 20,
        },
        {
          size: "42",
          count: 15,
        },
        {
          size: "43",
          count: 10,
        },
        {
          size: "44",
          count: 12,
        },
      ],
    },
    {
      id: "0d55026d-ff26-487f-9183-064e801a150e",
      brand: "StrideMax",
      model: "GelBliss 230",
      gender: "men",
      category: "running",
      material: "synthetic",
      season: "all_season",
      short_description: "Premium Cushioned Running Shoes",
      description:
        "The StrideMax GelBliss 230 offers premium cushioning and support for long-distance runners.",
      features: ["GEL cushioning technology", "Breathable mesh upper"],
      price: new Decimal("149.95"),
      initial_price: new Decimal("169.99"),
      rating_reviews: 90,
      rating_value: new Decimal("4.7"),
      thumbnail:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/78913680-cf99-47a0-b03c-9484cc689f24/buty-p-6000-B011cg.png",
      color: "white",
      stock_array: [
        {
          size: "40",
          count: 15,
        },
        {
          size: "41",
          count: 18,
        },
        {
          size: "42",
          count: 22,
        },
        {
          size: "43",
          count: 15,
        },
        {
          size: "44",
          count: 20,
        },
      ],
    },
  ];

  const result = processSQLProductBasicData(inputRows);

  expect(result).toEqual(expectedOutput);
});
